name: Semantic Release

on:
  push:
    branches:
      - test

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        run: |
          pip install -r requirements.txt
          poetry config virtualenvs.create false

      - name: Install Dependencies
        run: poetry install --no-dev

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run semantic-release publish

      - name: Capture Tag
        id: capture_tag
        run: echo ::set-output name=tag::$(git describe --abbrev=0 --tags)

      - name: Create Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a ${{ steps.capture_tag.outputs.tag }} -m "Release ${{ steps.capture_tag.outputs.tag }}"
          git push origin ${{ steps.capture_tag.outputs.tag }}
